"""add is_public and deleted_at to analyses

Revision ID: 06649dd608d0
Revises: 0f7abee2e7e0
Create Date: 2026-04-29 18:35:41.422878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06649dd608d0'
down_revision: Union[str, Sequence[str], None] = '0f7abee2e7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('is_public', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'deleted_at')
    op.drop_column('analyses', 'is_public')
    # ### end Alembic commands ###
