"""add indexes and duration_ms to jobs

Revision ID: efb22115ecc5
Revises: 06649dd608d0
Create Date: 2026-05-01 01:57:16.441716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb22115ecc5'
down_revision: Union[str, Sequence[str], None] = '06649dd608d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analyses_status', 'analyses', ['status'], unique=False)
    op.create_index('ix_analyses_user_id', 'analyses', ['user_id'], unique=False)
    op.create_index('ix_analysis_results_analysis_id', 'analysis_results', ['analysis_id'], unique=False)
    op.create_index('ix_audio_files_analysis_id', 'audio_files', ['analysis_id'], unique=False)
    op.add_column('jobs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.create_index('ix_jobs_analysis_id', 'jobs', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_analysis_id', table_name='jobs')
    op.drop_column('jobs', 'duration_ms')
    op.drop_index('ix_audio_files_analysis_id', table_name='audio_files')
    op.drop_index('ix_analysis_results_analysis_id', table_name='analysis_results')
    op.drop_index('ix_analyses_user_id', table_name='analyses')
    op.drop_index('ix_analyses_status', table_name='analyses')
    # ### end Alembic commands ###
